import Home from './home/Home';
import Products from './products/Products';
import Categories from './categories/Categories';
import Brands from './brands/Brands';
import BrandProducts from './Brand_Products/Brand_Products';
import SingleProductPage from './Product_Page/ProductPage';
import Cart from './cart/Cart';
import Wishlist from './wishlist/Wishlist';
import SubCate from './Sub_Cate_Page/SubCate';
import OrdersPage from './Orders/OrdersPage';
export { Home, Products, Categories, Brands, BrandProducts, SingleProductPage, Cart, Wishlist, SubCate, OrdersPage };
